name: compose-network

services:
  myweb:
    image: nginx:alpine
    networks:
      - mynetwork
    ports:
      - "8080:80" # 8080 is the host port (e.g., your PC), 80 is the container port

  myapp:
    image: busybox
    command: sleep 600
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge